# Generated by Django 5.1.4 on 2025-01-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "Username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
